export const SET_FULL_SCREEN = 'changeFullScreen'
export const SET_MINI_PLAYER = 'SET_MINI_PLAYER'
export const SET_IS_PLAYING  = 'SET_IS_PLAYING'
export const SET_MODE_TYPE   = 'SET_MODE_TYPE'
export const SET_LIST_PLAYER = 'SET_LIST_PLAYER'